### PR TITLE
Mysql

### PR DESCRIPTION
**Pull request by hendisantika**
Please check & review the changes @Ikhiloya .
Things those have been change are:
1. Change to MySQL Database
2. Add Swagger UI for API Documentation.

Thanks

### CODE REVIEW

**Comment by Ikhiloya** [comment]
Hi @hendisantika, thanks for your amazing contribution. Could you please separate the MySQL and Swagger feature. We could merge the Swagger feature to master and also maintain the MySQL feature on another branch, say a spring-boot-mysql branch. This way new users would be able to see the existing master for oracle and the new branch for MySql setup.  subsequently, we would have branches for other datasources. I would like to hear your feedback on this. Thanks for your time, hope to hear from you soon.

**Comment by hendisantika** [comment]
OK. I will separate the MySQL & Swagger feature

**Comment by Ikhiloya** [comment]
Thanks, I will merge once I get the PR

**Comment by hendisantika** [comment]
Please check again @Ikhiloya

**Comment by Ikhiloya** [comment]
this is for the Mysql feature, could you please create another PR for the Swagger config feature? I'll merge the swagger feature to the master.

**Pull request merged**
